routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::post('marketing/filter', 'productController@filter')->name('product.filter');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('contact', 'ContactController');

Route::resource('admin', 'AdminController')->middleware('adminCheck');

Route::resource('maintenance', 'MaintenanceController')->middleware('maintenanceCheck');

Route::resource('priceOverview', 'priceOverview')->middleware('customerCheck');

Route::resource('customer' , 'CustomerController')->middleware('customerCheck');

Route::resource('headmaintenance', 'HeadMaintenanceController')->middleware('headMaintenanceCheck');

Route::resource('product', 'ProductController')->middleware('marketingCheck');

Route::resource('marketing', 'MarketingController')->middleware('marketingCheck');

Route::resource('order', 'OrderController');

Route::resource('report', 'ReportController');

Route::resource('finance', 'financeController');

Route::resource('salescustomer', 'SalesController');

Route::get('index', function () {
    return view('index');
});

Route::get('sales', function () {
    return view('sales');
});

app/Http/Controllers/financeController.php
<?php

namespace App\Http\Controllers;

use App\Finance;
use App\Lease;
use Illuminate\Http\Request;

class financeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('finance/index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = \App\User::all();
        $lease_types = \App\LeaseTypes::all();
        return view('finance/create', ['users' => $users, 'lease_types' => $lease_types]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $checked = 0;

        if ($request->contract_agreed != null){
            $checked = 1;
        }

        Lease::insert([
            'user_ID'           => $request->user_ID,
            'start_date'        => $request->start_date,
            'end_date'          => $request->end_date,
            'lease_type_ID'     => $request->lease_type_ID,
            'contract_agreed'   => $checked
        ]);

        return view('finance.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/finance/create.blade.php
@extends('layouts.layout')
@section('title', 'Barroc Intense')
@section('content')
    <div>
    <h1>Contract</h1>
    <form action="{{route('finance.store')}}" method="post">
    @csrf

        <select name="user_ID" id="">
            @foreach($users as $user)

                <option value="{{$user->id}}">{{$user->name}}</option>
            @endforeach
        </select>
        <input type="date" name="start_date" placeholder="start date">
        <input type="date" name="end_date" placeholder="start end">
        <select name="lease_type_ID" id="">
            @foreach($lease_types as $lease_type)
                <option value="{{$lease_type->id}}">{{$lease_type->lease_type}}</option>
            @endforeach
        </select>

        <div style="display: flex"><input type="checkbox" name="contract_agreed" value="1"><p>Contract Getekend</p></div>

        <input type="submit" name="submit" value="Maak Contract">
    </form>
    </div>
@endsection

resources/views/finance/index.blade.php
@extends('layouts.layout')
@section('title', 'Barroc Intense')
@section('content')
<div>
<h1>Finance</h1>

<input type="button" onclick="location.href='{{route('finance.create')}}'" value="Maak contract aan">
</div>
@endsection