routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::post('marketing/filter', 'productController@filter')->name('product.filter');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('contact', 'ContactController');

Route::resource('admin', 'AdminController')->middleware('adminCheck');

Route::resource('maintenance', 'MaintenanceController')->middleware('maintenanceCheck');

Route::resource('priceOverview', 'priceOverview')->middleware('customerCheck');

Route::resource('customer' , 'CustomerController')->middleware('customerCheck');

Route::resource('headmaintenance', 'HeadMaintenanceController')->middleware('headMaintenanceCheck');

Route::resource('product', 'ProductController')->middleware('marketingCheck');

Route::resource('marketing', 'MarketingController')->middleware('marketingCheck');

Route::resource('order', 'OrderController');

Route::resource('report', 'ReportController');

Route::resource('finance', 'financeController');

Route::resource('salescustomer', 'SalesController');

Route::get('index', function () {
    return view('index');
});

Route::get('sales', function () {
    return view('sales');
});

app/Appointment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Appointment extends Model
{
    public $table = "Appointment";

    public function lease(){
        return $this->hasOne('\App\Lease', 'id');
    }

    public function status(){
        return $this->hasOne('\App\Status', 'id');
    }
}

app/CompanyDetail.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CompanyDetail extends Model
{
    protected $table = 'company_details';

    protected $fillable = ['kvk_number', 'iban_number'];
}

app/LeaseRules.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class LeaseRules extends Model
{

}

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    //
}

app/Overview.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Overview extends Model
{
    //
}

app/Purchase.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Purchase extends Model
{
    //
}

app/Status.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Status extends Model
{
    public $table = "Status";
}

app/Supply.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Supply extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function companyDetail(){
        return $this->hasOne('\App\CompanyDetail','user_ID');
    }


}

app/WorkOrder.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class WorkOrder extends Model
{
    //
}

app/category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class category extends Model
{
    
}

app/contact_form.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class contact_form extends Model
{
    public $table = "contact_form";
}

app/cr.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class cr extends Model
{
    //
}

app/invoices.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class invoices extends Model
{
    public function leases(){
        return $this->hasOne('\App\leases','id');
    }
}

app/leaseTypes.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class leaseTypes extends Model
{
    protected $table = 'lease_types';
}

app/leases.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class leases extends Model
{
    protected $table = 'leases';

    public function leaseTypes(){
        return $this->hasOne('\App\leaseTypes','id');
    }

    public function leaseRules(){
        return $this->hasMany('\App\LeaseRules','lease_ID');
    }

    public function leaseProducts(){
        return $this->hasMany('\App\product','id');
    }
}

app/product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    public $table = "products";

    protected $fillable = ['name', 'lease_costs', 'connect_costs', 'costs', 'description'];

    public function products()
    {
        //return $this->BelongsTo('\App\product');
    }
}

app/Http/Controllers/Admin.php
<?php

namespace App\Http\Controllers;

use App\cr;
use Illuminate\Http\Request;

class Admin extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\cr  $cr
     * @return \Illuminate\Http\Response
     */
    public function show(cr $cr)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\cr  $cr
     * @return \Illuminate\Http\Response
     */
    public function edit(cr $cr)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\cr  $cr
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, cr $cr)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\cr  $cr
     * @return \Illuminate\Http\Response
     */
    public function destroy(cr $cr)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/index.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class index extends Controller
{
    public function index()
    {
        return view('index');
    }
}

resources/views/SalesCustomer/create.blade.php
@extends('layouts.layout')
@section('title', 'Barroc Intense')
@section('content')
<div>
    <h1>Sales create</h1>
    <form action="{{route('salescustomer.store')}}" method="post">
        @csrf
        <input type="text" name="name" placeholder="name">
        <input type="text" name="lastname" placeholder="lastname">
        <input type="text" name="adress" placeholder="adress">
        <input type="text" name="zipcode" placeholder="zipcode">
        <input type="text" name="city" placeholder="city">
        <input type="text" name="phone" placeholder="phone">
        <input type="text" name="password" placeholder="password">
        <input type="hidden" name="role_ID" value="4">
        <input type="text" name="email" placeholder="email">
        <input type="submit" name="submit" value="Maak klant">
    </form>
</div>
@endsection

resources/views/SalesCustomer/index.blade.php
@extends('layouts.layout')
@section('title', 'Barroc Intense')
@section('content')
<div>
    <h1>Sales Index</h1>
    @foreach($users as $user)
    <li><a href="{{route('salescustomer.show', $user->id)}}">{{$user->name}}</a></li>
    @endforeach
    <input type="button" onclick="location.href='{{route('salescustomer.create')}}'" value="Maak klant aan">
</div>
@endsection

resources/views/SalesCustomer/show.blade.php
@extends('layouts.layout')
@section('title', 'Barroc Intense')
@section('content')

    <h1>Sales show</h1>

@endsection

resources/views/admin/index.blade.php
@extends('layouts.layout')
@section('title', 'Barroc Intense')
@section('content')

<h1>Admin: Pagina selectie</h1>
<ul>
    <li><a href="{{ route('contact.index') }}">contact</a></li>
    <li><a href="{{ route('marketing.index') }}">inkoop/marketing</a></li>
    <li><a href="{{ route('maintenance.index') }}">maintenance</a></li>
    <li><a href="{{ route('headmaintenance.index') }}">headmaintenace</a></li>
    <!-- <li><a href="{{ route('customer.index') }}">customer</a></li> -->
    <li><a href="{{ route('marketing.index') }}">inkoop/marketing</a></li>
    <li><a href="{{ route('priceOverview.index') }}">priceOverview</a></li>
    <li><a href="{{ route('salescustomer.index') }}">salescustomer</a></li>

</ul>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
@extends('layouts.layout')
@section('title', 'Barroc Intense')

@section('content')
<div class="main-content">
    <div class="main-content-centered">

        <div class="item" id="homepage-title">
            <h1>COFFE FACTORY</h1>
        </div>

        <div class="item" id="homepage-img">
            <img src="{{ asset('img/Logo6_groot.png') }}" alt="">
        </div>

        <div class="item" id="homepage-desc">
            <button class="button" onclick="window.location.href = '#';">Producten <i class="fas fa-chevron-right"></i></button>
        </div>

    </div>
</div>
    <div class="products">
        @for ($i = 0; $i <= 8; $i++)
            <div class="product">
                <div class="product-image">
                    <img src="{{ asset('img/bit-deluxe.png') }}" alt="">
                </div>
                <div class="product-title">
                    <h3>Bit deluxe</h3>
                </div>
                <div class="product-desc">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab amet aspernatur
                        assumenda atque consectetur dicta, dolores eaque facere hic ipsa labore maiores
                        mollitia officia pariatur, provident quas quia voluptatibus! Consequuntur.</p>
                </div>
                <div class="product-button">
                    <button class="button" onclick="window.location.href = '#';">Meer <i class="fas fa-chevron-right"></i></button>
                </div>
            </div>
        @endfor
    </div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/layout.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="{{ asset('css/main.css') }}" rel="stylesheet">

    <link href="{{ asset('css/contact.css') }}" rel="stylesheet">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
          integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    <title>@yield('title')</title>
</head>
<body>
<header>
    <div class="header-content">
        <div class="logo">
            <img src="{{ asset('img/Logo6_klein.png') }}" alt="">
        </div>
        <div class="nav-menu">
            <div class="link">
                <a href="">Home</a>
            </div>
            @if(Auth::user())
            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
                <input type="submit" value="Uitloggen">
            </form>
            <div class="link">
            <a href=""
                onclick="event.preventDefault();
                                document.getElementById('logout-form').submit();">
                Uitloggen
            </a>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
            </form>
            </div>
            @endif
            
            @if(!Auth::user())
            <div class="link">
                <a href="{{ route('login') }}">Inloggen</a>
            </div>
            @endif
        </div>
    </div>
</header>
<main>
    @yield('content')
</main>
<footer>
    <div class="footer-content">
        <h2>&copy; Barroc Intense 2019</h2>
    </div>
</footer>
</body>
</html>

resources/views/priceOverview/create.blade.php
@extends('layouts.layout')
@section('title', 'Barroc Intense')
@section('content')

    <div class="main-content">
        <div class="customer-dashboard">
                <form action="{{route('priceOverview.store')}}" method="put">
                    @csrf
                    @foreach($products as $product)
                        <div class="formitem">
                            <label for="{{$product->id}}">{{$product->name}}</label>
                            <input type="number" name="{{$product->name}}" id="{{$product->id}}">
                        </div>
                    @endforeach
                    <input type="submit" value="Vraag prijsopgave aan">
                </form>
        </div>
    </div>

@endsection

resources/views/priceOverview/index.blade.php
@extends('layouts.layout')
@section('title', 'Barroc Intense')
@section('content')

    <div class="main-content">
        <div class="customer-dashboard">
            <div class="titel">
                <h1>Priceoverview</h1>
            </div>
            <div>
                <button type="button"><a href="{{route('priceOverview.create')}}">Prijsopgave aanvragen</a></button>

            </div>
        </div>
    </div>

@endsection

resources/views/sales.blade.php
@extends('layouts.layout')
@section('title', 'Barroc Intense')

@section('content')
    <div class="contactForm">
        <form action="" method="post">
            @csrf
            <input type="text" name="firstname" placeholder="firstname">
            <input type="text" name="lastname" placeholder="lastname">
            <input type="text" name="adress" placeholder="adress">
            <input type="text" name="zipcode" placeholder="zipcode">
            <input type="text" name="city" placeholder="city">
            <input type="text" name="phone" placeholder="phone">
            <input type="password" name="password" placeholder="password">
            <input type="password" name="password-repeat" placeholder="password-repeat">
            <select name="role" id="role">
                <option value="1"></option>
            </select>
            <input type="email" name="email" placeholder="email">
            <input type="text" name="kvk_number" placeholder="kvk number">
            <input type="submit" name="submit" value="Create Contact">
        </form>
    </div>

@endsection