routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::post('marketing/filter', 'productController@filter')->name('product.filter');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('contact', 'ContactController');

Route::resource('admin', 'AdminController')->middleware('adminCheck');

Route::resource('maintenance', 'MaintenanceController')->middleware('maintenanceCheck');

Route::resource('priceOverview', 'priceOverview')->middleware('customerCheck');

Route::resource('customer' , 'CustomerController')->middleware('customerCheck');

Route::resource('headmaintenance', 'HeadMaintenanceController')->middleware('headMaintenanceCheck');

Route::resource('product', 'ProductController')->middleware('marketingCheck');

Route::resource('marketing', 'MarketingController')->middleware('marketingCheck');

Route::resource('order', 'OrderController');

Route::resource('report', 'ReportController');

Route::resource('finance', 'financeController');

Route::resource('salescustomer', 'SalesController');

Route::get('index', function () {
    return view('index');
});

Route::get('sales', function () {
    return view('sales');
});

app/Http/Controllers/MaintenanceController.php
<?php

namespace App\Http\Controllers;

use App\Appointment;
use App\Product;
use App\Status;
use App\Work_Order;
use App\WorkOrder;
use Illuminate\Http\Request;

class MaintenanceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $appointment = Appointment::all();
        return view('maintenance/index',['appointment'=>$appointment]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        WorkOrder::insert([
           'appointment_ID'     => $request->appointment_ID,
            'product_ID'        => $request->product_ID
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $appointment = \App\Appointment::find($id);
        $status = \App\Status::all();
        $products = \App\product::all();

        return view('maintenance/show', ['appointment' => $appointment,'status' => $status,'products' => $products]);
//        $appointment = Appointment::find($id);
//
//        $products = Product::find($id);
//        $products = Product::All();
//
//        $status = Status::find($id);
//        $status = Status::All();

        //dd($products);
        //dd($status);

        //return view('Maintenance/show')->with('appointment', $appointment)->with('products', $products)->with('status', $status)->with('appointmentId', $id);

        // return view('Maintenance/show',['appointment'=>$appointment, 'products' => $products, 'status' => $status]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $status = Status::find($id);

        $products = Product::find($id);
        return view('maintenance/show',['status' => $status, 'products' => $products]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        WorkOrder::insert([
            'appointment_ID' => $id,
            'product_ID'     => $request->product_ID,
            'status_ID'      => $request->status_ID,
            'amount'         => $request->amount
        ]);

        $appointment = \App\Appointment::find($id);
        $status = \App\Status::all();
        $products = \App\product::all();

        return view('maintenance/show', ['appointment' => $appointment,'status' => $status,'products' => $products]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/Maintenance/index.blade.php
@extends('layouts.layout')
@section('title', 'Barroc Intense')
@section('content')
    <div>
    <h1>Worker Maintenance</h1>
    @foreach($appointment as $appointment)
    <li><a href="{{route('maintenance.show', $appointment->id)}}">{{$appointment->appointment_task}}</a></li>
    @endforeach
    </div>
@endsection

resources/views/Maintenance/show.blade.php
@extends('layouts.layout')
@section('title', 'Barroc Intense')
@section('content')
    <div>
        <form action="{{route('maintenance.update', $appointment->id)}}" method="post">
            @csrf
            @method('PUT')
            <select name="product_ID" id="">
                @foreach($products as $product)
                    <option name="product_ID" value="{{$product->id}}">{{$product->name}}</option>
                @endforeach
            </select>
            <select name="status_ID" id="">
                @foreach($status as $item)
                    <option value="{{$item->id}}">{{$item->status_description}}</option>
                @endforeach
            </select>

            <input type="number" name="amount" placeholder="aantal">

            <input type="submit" value="Maak Werkbon">
        </form>
        <input type="button" onclick="location.href='{{route('maintenance.index')}}'" value="Terug">
    </div>
@endsection